server:
  port: 8762
<<<<<<< HEAD
management:
  endpoints:
    web:
      exposure:
        include: health, info
spring:
  application:
    name: api-gateway-service
  profiles:
    active: local
  cloud:
=======

management.endpoints.web.exposure.include: gateway,metrics

spring:
  application:
    name: api-gateway-service
  profiles:
    active: local
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
>>>>>>> refs/heads/develop
    config:
      fail-fast: true
    devtools:
      livereload:
        port: 0